name: CI/CD

on: ['push']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: lint, test
        run: |
          make lint
          make test

      - name: check build
        run: |
          make build
          ./md5http -parallel 2 \
            https://google.com \
            https://yandex.ru \
            https://bing.co.uk
